title: Jardin des Simples
description: "Médecine, poison, sorcellerie — Plateau du Forez"
url: "https://julien-lambert.github.io"
baseurl: "/jardin_des_simples"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: true
      toc_sticky: true
      toc_levels: 2..3
      header:
        overlay_filter: 0.85
