title: Jardin des Simples
description: "Médecine, poison, sorcellerie — Plateau du Forez"
url: "https://<TON-USER>.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: true
      toc_sticky: true
      toc_levels: 2..3
